language: nix

script: nix-shell --command "cabal run site build"

deploy:
  - provider: netlify
    site: f37f3fdf-7319-4066-8dc7-e837dd2cdce8
    auth: $NETLIFY_AUTH
    dir: "_site/"
    prod: true
    edge: true # opt in to dpl v2
    on:
      branch: master